### ISSUE TITLE
UX DESIGNER - Fortaleza/CE

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/TrabalheConosco#1]
## DESCRIÇÃO DA VAGA
Como Analista de UX você poderá produzir e prototipar interfaces para o usuário, ter contato direto com clientes para realizar pesquisas e entrevistas, realizar buscas por novas funcionalidades de produtos e ainda terá uma grande relação com os produtos digitais, com o ciclo de vida, a jornada de clientes e usuários e  prototipação e validação de hipóteses dos projetos da empresa.

### Remuneração e Carga Horária

6.200,00 (bruto), Regime CLT, 40h.

### OS OBJETIVOS INCLUEM:
- Identificar problemas de usabilidade.
- Criar hipóteses e testes para soluções de problemas.
- Aumentar o tempo de permanência nos sites.
- Aumentar o número de conversões nas landing pages.

#### RESPONSABILIDADES:
- Ser a “voz do usuário” e entender as expectativas e pontos problemáticos que ele vê com os sites, blogs e aplicativos da empresa.
- Realizar pesquisas de design centrado no usuário e testes de usabilidade.
- Preparar e documentar as conclusões e documentações
- Analisar e apresentar os resultados da investigações e pesquisas para os gestores.
- Realizar testes A/B nos projetos.

#### REQUISITOS:
- Conhecimentos a respeito de arquitetura da informação e de disciplinas que envolvem a experiência de usuário
- Experiência com design de interface
- Saber trabalhar com equipes
- Conhecer ferramentas de Design Thinking
- Conhecimentos de HTML, CSS e JavaScript
- Habilidade para trabalhar em múltiplos projetos

Enviar currículo para o e-mail nutic@esp.ce.gov.br, com o assunto "UX DESIGNER"

**Comment by n3pu** [comment]
Forma da aplicação amigo?

**Comment by onaSousa** [comment]
Tenho interesse. O que é preciso pra vaga, enviar currículo, um teste?

**Comment by diegocuruma** [comment]
Como faz pra participar?

**Comment by elanlopes** [comment]
Opa! Pois vamos trabalhar Uirá.
Como você não deixou informações sobre como aplicar a vaga, tomei a liberdade de enviar meu currículo em anexo.
[elanlopes-curriculo-2019-(v2).pdf](https://github.com/EscolaDeSaudePublica/TrabalheConosco/files/4035425/elanlopes-curriculo-2019-.v2.pdf)

**Comment by elanlopes** [comment]
Opa! Pois vamos trabalhar, Uirá.

Segue o link do meu perfil no LinkedIn: 
https://www.linkedin.com/in/elanlopes/

**Comment by uira** [comment]
> Forma da aplicação amigo?

Aqui @n3pu, corrigimos depois lá:

Enviar currículo para o e-mail nutic@esp.ce.gov.br, com o assunto "UX DESIGNER"
